import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Agents Book | Admin',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<main className="overflow-hidden">{children}</main>
			</body>
		</html>
	);
}
