import type { Metadata } from 'next';
import { isAdmin } from '@/lib/actions/admin.action';
import { auth } from '@clerk/nextjs/server';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
	title: 'Agents Book | Admin',
	description: 'Generated by create next app'
};

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	const { userId } = auth();

	const checkIsAdmin = await isAdmin(userId);

	if (!checkIsAdmin) {
		redirect('/');
	}

	return (
		<html lang="en">
			<body>
				<main className="overflow-hidden">{children}</main>
			</body>
		</html>
	);
}
